# Generated by Django 5.0.7 on 2024-07-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='crated_by',
            new_name='created_by',
        ),
    ]
