# Generated by Django 5.0.7 on 2024-07-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_rename_crated_by_item_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={},
        ),
    ]
